#!/usr/bin/env python3
"""Build the consolidated Mihomo Japan domain rule list."""

from __future__ import annotations

import re
import urllib.request
from pathlib import Path

UPSTREAM_URL = "https://ruleset.skk.moe/Clash/non_ip/stream_jp.txt"
ROOT = Path(__file__).resolve().parent.parent
MANUAL_FILE = ROOT / "manual" / "japan-content.list"
OUTPUT_FILE = ROOT / "rules" / "japan-only.list"

DOMAIN_RE = re.compile(r"^(?:[A-Za-z0-9_-]+\.)+[A-Za-z]{2,}$")
TEST_MARKER = "ru1353t.1s.m4d3.by.5ukk4w.skk.moe"
REQUIRED_RULES = {
    "+.dmm.com",
    "+.dmm.co.jp",
    "+.fanza.jp",
    "+.bookwalker.jp",
    "+.manga.line.me",
}


def is_valid_domain(domain: str) -> bool:
    return bool(DOMAIN_RE.fullmatch(domain))


def normalize_manual_rule(line: str) -> str | None:
    line = line.split("#", 1)[0].strip()
    if not line:
        return None

    if line.startswith("+."):
        domain = line[2:].rstrip(".")
        return f"+.{domain}" if is_valid_domain(domain) else None

    domain = line.rstrip(".")
    return domain if is_valid_domain(domain) else None


def fetch_upstream() -> list[str]:
    request = urllib.request.Request(
        UPSTREAM_URL,
        headers={"User-Agent": "mihomo-japan-rules/2.0"},
    )
    with urllib.request.urlopen(request, timeout=60) as response:
        text = response.read().decode("utf-8")

    rules: list[str] = []
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue

        parts = [part.strip() for part in line.split(",", 2)]
        rule_type = parts[0]
        if len(parts) < 2:
            continue

        domain = parts[1].rstrip(".")
        if not is_valid_domain(domain):
            continue

        if rule_type == "DOMAIN-SUFFIX":
            rules.append(f"+.{domain}")
        elif rule_type == "DOMAIN":
            rules.append(domain)

    return rules


def main() -> None:
    manual_rules = [
        rule
        for raw_line in MANUAL_FILE.read_text(encoding="utf-8").splitlines()
        if (rule := normalize_manual_rule(raw_line)) is not None
    ]

    upstream_rules = fetch_upstream()

    combined = set(manual_rules)
    combined.update(rule for rule in upstream_rules if TEST_MARKER not in rule)

    required_missing = sorted(REQUIRED_RULES - combined)
    if required_missing:
        raise SystemExit(
            "Refusing to publish incomplete rules: missing required rules: "
            + ", ".join(required_missing)
        )

    minimum_expected = len(set(manual_rules)) + 5
    if len(combined) < minimum_expected:
        raise SystemExit(
            f"Refusing to publish suspiciously small ruleset: "
            f"{len(combined)} entries (expected at least {minimum_expected})."
        )

    output = [
        "# mihomo-japan-rules",
        "# Generator: 2",
        "# Generated by GitHub Actions",
        f"# Upstream: {UPSTREAM_URL}",
        "",
        *sorted(combined, key=str.casefold),
        "",
    ]
    OUTPUT_FILE.write_text("\n".join(output), encoding="utf-8")

    print(
        f"Generated {len(combined)} rules "
        f"({len(set(upstream_rules))} upstream, "
        f"{len(set(manual_rules))} manual)."
    )


if __name__ == "__main__":
    main()
